jetclustering_slides:
	awk -f makeslides.awk jet_clustering/nominal.config jet_clustering/plots_HH.config > testTexSlides.tex
	pdflatex testTexSlides.tex
	rm testTexSlides.snm
	rm testTexSlides.aux
	rm testTexSlides.out
	rm testTexSlides.nav
	rm testTexSlides.toc
	rm testTexSlides.log
